name: PR Description Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest

    steps:
    - name: Check for required keywords in /kind
      id: kind_check
      run: |
        KEYWORDS=("new feature" "bug fix" "cleanup" "revert change" "design" "documentation" "enhancement")
        TEST_KEYWORDS=("TESTED" "NOT-TESTED")

        KIND_LINES=$(echo "${{ github.event.pull_request.body }}" | grep '/kind' | tr '[:upper:]' '[:lower:]')

        CONTAINS_KIND_KEYWORD=0
        CONTAINS_TEST_KEYWORD=0

        for keyword in "${KEYWORDS[@]}"; do
          if echo "$KIND_LINES" | grep -q "$keyword"; then
            CONTAINS_KIND_KEYWORD=1
            break
          fi
        done

        for test_keyword in "${TEST_KEYWORDS[@]}"; do
          if echo "${{ github.event.pull_request.body }}" | grep -q "$test_keyword"; then
            CONTAINS_TEST_KEYWORD=1
            break
          fi
        done

        echo "CONTAINS_KIND_KEYWORD=$CONTAINS_KIND_KEYWORD" >> $GITHUB_ENV
        echo "CONTAINS_TEST_KEYWORD=$CONTAINS_TEST_KEYWORD" >> $GITHUB_ENV

    - name: Fail if required keywords are missing
      if: ${{ env.CONTAINS_KIND_KEYWORD == '0' || env.CONTAINS_TEST_KEYWORD == '0' }}      
      run: |
        echo "Pull request rejected: Please ensure to follow pr template."
        exit
